swagger: '2.0'
info:
  version: 1.0.0
  title: ShopEasy Product Management APIs
schemes:
  - http
host: 'localhost:5000'
basePath: /
tags:
  - name: modify
    description: Modify ShopEasy products
  - name: browse
    description: Browse by category or product
  - name: order
    description: Access to ShopEasy orders
  - name: user
    description: Operations with user
paths:
  '/products':
    get:
      tags:
        - browse
      summary: View all products
      responses: 
        200:
          description: OK
          schema:
            $ref: '#/definitions/products'
  '/products/{productID}':
    get:
      tags:
        - browse
      summary: get product by ID
      description: Try IDs in the range 1 - 10 for testing
      parameters:
        - required: true
          in: path
          name: productID
          type: string
      responses:
        '200':
          description: list product details
          schema:
            $ref: '#/definitions/product'
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
    post:
      tags:
        - modify
      summary: Add a new product to the store
      description: ''
      operationId: addProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - required: true
          in: path
          name: productID
          type: string
        - required: true
          in: body
          name: body
          description: Product object that needs to be added to the store
          schema:
            $ref: '#/definitions/product'
      responses:
        '201':
          description: new product added
        '400':
          description: Invalid ID supplied
        '405':
          description: Invalid input
    put:
      tags:
        - modify
      summary: Update an existing product
      description: ''
      operationId: updateProduct
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - required: true
          in: path
          name: productID
          type: string
        - required: true
          in: body
          name: body
          description: Product object that needs to be modified
          schema:
            $ref: '#/definitions/product'
      responses:
        '200':
          description: product modified
        '400':
          description: Invalid ID supplied
        '404':
          description: Product not found
    delete:
      tags:
        - modify
      summary: Delete a product
      description: ''
      operationId: deleteProduct
      produces:
        - application/json
      parameters:
          - in: path
            name: productID
            description: Product id to delete
            required: true
            type: integer
            format: int64
      responses:
        '200':
          description: Product deleted
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
  '/products/{productID}/checkSize':
    get:
      tags:
        - browse
      summary: check size availability
      parameters:
        - required: true
          in: path
          name: productID
          type: string
        - required: true
          in: query
          name: size
          type: string
      responses:
        '200':
          description: size available
          schema:
            type: boolean
        '400':
          description: Invalid product ID
        '404':
          description: size unavailable
  '/products/{productID}/checkColour':
    get:
      tags:
        - browse
      summary: check colour availability
      parameters:
        - required: true
          in: path
          name: productID
          type: string
        - required: true
          in: query
          name: colour
          type: string
      responses:
        '200':
          description: colour is available
          schema:
            type: boolean
        '400':
          description: Invalid product ID
        '404':
          description: colour not available
  '/products/{productID}/getStatus':
    get:
      tags: 
        - browse
      summary: get state of product
      parameters:
        - required: true
          in: path
          name: productID
          type: string
      responses:
        "200":
          description: return product status
          schema:
            $ref: '#/definitions/status'
        "404":
          description: Product not found with matching ID
  '/categories/{category}':
    get:
      tags:
        - browse
      summary: Browse product categories
      parameters:
        - required: true
          in: path
          name: category
          type: string
      responses:
        "200":
          description: Category Details
          schema:
            $ref: '#/definitions/category'
        "404":
          description: Category does not exist
  '/brands':
    get:
      tags: 
        - browse
      summary: Browse brands
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/brands'
        "404":
          description: Brand not found
  '/products/findByBrand':
    get:
      tags: 
        - browse
      summary: Get products of a brand
      parameters:
        - required: true
          in: query
          name: brandID
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/brandProducts'
        "404":
          description: Brand not found
  '/products/findByTaxSlab':
    get:
      tags: 
        - browse
      summary: Get products in a particular tax slab
      parameters:
        - required: true
          in: query
          name: slab
          type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/slabProducts'
        "404":
          description: Not Found
definitions:
  category:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      subcategories:
        type: array
        items:
          type: object
  brands:
    type: array
    items:
      type: object
  brandProducts:
    type: array
    items:
      type: string
  slabProducts:
    type: array
    items:
      type: object
  product:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      category:
        $ref: '#/definitions/category'
      name:
        type: string
      sku:
        type: string
      price:
        type: number
      GST:
        type: number
        enum: 
          - 0
          - 5
          - 12
          - 18
          - 28
      brand:
        type: string
      size:
        type: string
      colour:
        type: string
      model:
        type: string
      mediaURLs:
        type: array
        items:
          type: string
      dateOfManufacture:
        type: number
        format: date
      metadata:
        type: object
        additionalProperties:
          type: string
      tags:
        type: array
        items:
          $ref: '#/definitions/tag'
      status:
        $ref: '#/definitions/status'
      checkoutType:
        type: string
        enum: 
          - physical
          - digital
  products:
    type: array
    items:
      type: object
  tag:
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
  status:
    type: string
    description: product status in the store
    enum:
      - available
      - draft
      - sold